#############################################################################
# Makefile for building: animals22.app/Contents/MacOS/animals22
# Generated by qmake (3.1) (Qt 6.2.2)
# Project:  animals22.pro
# Template: app
# Command: /Users/thomasrio/Qt/6.2.2/macos/bin/qmake -o Makefile animals22.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers -I../../../../Qt/6.2.2/macos/lib/QtGui.framework/Headers -I../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/6.2.2/macos/mkspecs/macx-clang -F/Users/thomasrio/Qt/6.2.2/macos/lib
QMAKE         = /Users/thomasrio/Qt/6.2.2/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/thomasrio/Qt/6.2.2/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/thomasrio/Qt/6.2.2/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = animals221.0.0
DISTDIR = /Users/thomasrio/1FO/C++/PROJET/animals22_RIO_GENTY/.tmp/animals221.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/thomasrio/Qt/6.2.2/macos/lib
LIBS          = $(SUBLIBS) -F/Users/thomasrio/Qt/6.2.2/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_images.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_images.o \
		moc_mainwindow.o
DIST          = infographic_extinction-main/Makefile \
		infographic_extinction-main/README.md \
		infographic_extinction-main/date_recup.py \
		infographic_extinction-main/extinct_animals.csv \
		../../../../Qt/6.2.2/macos/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/device_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/common/unix.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/macx.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/sanitize.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/clang.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/clang-mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/qconfig.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/6.2.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/6.2.2/macos/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/sdk.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/toolchain.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/default_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/default_post.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_post.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qml_debug.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/mac.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/warn_on.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resources.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/moc.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/uic.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/unix/thread.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/file_copies.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/rez.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/exceptions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/yacc.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/lex.prf \
		animals22.pro Animal.hh \
		Carnivorous.hh \
		Herbivorous.hh \
		catch.hpp \
		infographic_extinction-main/CSVReader.hh \
		infographic_extinction-main/Specie.hh \
		mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = animals22
DESTDIR       = 
TARGET        = animals22.app/Contents/MacOS/animals22

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/thomasrio/1FO/C++/PROJET/animals22_RIO_GENTY/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/thomasrio/1FO/C++/PROJET/animals22_RIO_GENTY/animals22.pro


include /Users/thomasrio/Qt/6.2.2/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

animals22.app/Contents/MacOS/animals22: ui_mainwindow.h $(OBJECTS)  
	@test -d animals22.app/Contents/MacOS/ || mkdir -p animals22.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: animals22.pro ../../../../Qt/6.2.2/macos/mkspecs/macx-clang/qmake.conf ../../../../Qt/6.2.2/macos/mkspecs/features/spec_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/device_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/common/unix.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/macx.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/sanitize.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/clang.conf \
		../../../../Qt/6.2.2/macos/mkspecs/common/clang-mac.conf \
		../../../../Qt/6.2.2/macos/mkspecs/qconfig.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt_functions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/6.2.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/6.2.2/macos/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/sdk.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/toolchain.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/default_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resolve_config.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/default_post.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_post.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qml_debug.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/mac.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/warn_on.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qt.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resources_functions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/resources.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/moc.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/unix/opengl.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/uic.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/unix/thread.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/qmake_use.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/file_copies.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/rez.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/testcase_targets.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/exceptions.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/yacc.prf \
		../../../../Qt/6.2.2/macos/mkspecs/features/lex.prf \
		animals22.pro \
		images.qrc \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Qt/6.2.2/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile animals22.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../../Qt/6.2.2/macos/mkspecs/features/spec_pre.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/device_config.prf:
../../../../Qt/6.2.2/macos/mkspecs/common/unix.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/mac.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/macx.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/sanitize.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/clang.conf:
../../../../Qt/6.2.2/macos/mkspecs/common/clang-mac.conf:
../../../../Qt/6.2.2/macos/mkspecs/qconfig.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/6.2.2/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/6.2.2/macos/mkspecs/features/qt_functions.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/qt_config.prf:
../../../../Qt/6.2.2/macos/mkspecs/macx-clang/qmake.conf:
../../../../Qt/6.2.2/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/6.2.2/macos/mkspecs/features/exclusive_builds.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/sdk.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/toolchain.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/toolchain.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/default_pre.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_pre.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/resolve_config.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/default_post.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/default_post.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/objective_c.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/qml_debug.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/mac.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/warn_on.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/qt.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/resources_functions.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/resources.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/moc.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/unix/opengl.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/uic.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/unix/thread.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/qmake_use.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/file_copies.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/rez.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/testcase_targets.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/exceptions.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/yacc.prf:
../../../../Qt/6.2.2/macos/mkspecs/features/lex.prf:
animals22.pro:
images.qrc:
../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Qt/6.2.2/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Qt/6.2.2/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile animals22.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

animals22.app/Contents/PkgInfo: 
	@test -d animals22.app/Contents || mkdir -p animals22.app/Contents
	@$(DEL_FILE) animals22.app/Contents/PkgInfo
	@echo "APPL????" > animals22.app/Contents/PkgInfo
animals22.app/Contents/Resources/empty.lproj: 
	@test -d animals22.app/Contents/Resources || mkdir -p animals22.app/Contents/Resources
	@touch animals22.app/Contents/Resources/empty.lproj
	
animals22.app/Contents/Info.plist: 
	@test -d animals22.app/Contents || mkdir -p animals22.app/Contents
	@$(DEL_FILE) animals22.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,TR.animals22,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},TR.animals22,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,animals22,g" -e "s,@LIBRARY@,animals22,g" -e "s,\$${EXECUTABLE_NAME},animals22,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../../Qt/6.2.2/macos/mkspecs/macx-clang/Info.plist.app >animals22.app/Contents/Info.plist

all: Makefile \
		animals22.app/Contents/PkgInfo \
		animals22.app/Contents/Resources/empty.lproj \
		animals22.app/Contents/Info.plist animals22.app/Contents/MacOS/animals22

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents Animal.hh Carnivorous.hh Herbivorous.hh catch.hpp infographic_extinction-main/CSVReader.hh infographic_extinction-main/Specie.hh mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r animals22.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		../../../../Qt/6.2.2/macos/libexec/rcc \
		IMG/an-coc.png \
		IMG/PAG_GAUCHE.png \
		IMG/AFRIQUE.png \
		IMG/an-bee.png \
		IMG/About_page.png \
		IMG/AMERIQUE.png \
		IMG/More_info.png \
		IMG/fond_img.png \
		IMG/ASIE.png \
		IMG/an-wolf.png \
		IMG/EUROPE.png \
		IMG/Question.png \
		IMG/bouffe_herbi.png \
		IMG/an-cow.png \
		IMG/bouffe_carni.png \
		IMG/WORLD.png \
		IMG/an-dog.png \
		IMG/diplo.png \
		IMG/croco_die.png \
		IMG/blanc.png \
		IMG/bc.png \
		IMG/croco.png \
		IMG/diplo_die.png \
		IMG/BACKGROUND.png \
		IMG/OCEANIE.png \
		IMG/bas.png \
		IMG/PAG_DROITE.png \
		IMG/an-rat.png \
		IMG/Game_bc.png \
		IMG/EARTH.png \
		infographic_extinction-main/extinct_animals.csv
	/Users/thomasrio/Qt/6.2.2/macos/libexec/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		infographic_extinction-main/Specie.hh \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/6.2.2/macos/libexec/moc
	/Users/thomasrio/Qt/6.2.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/thomasrio/Qt/6.2.2/macos/mkspecs/macx-clang -I/Users/thomasrio/1FO/C++/PROJET/animals22_RIO_GENTY -I/Users/thomasrio/Qt/6.2.2/macos/lib/QtWidgets.framework/Headers -I/Users/thomasrio/Qt/6.2.2/macos/lib/QtGui.framework/Headers -I/Users/thomasrio/Qt/6.2.2/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/thomasrio/Qt/6.2.2/macos/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../../Qt/6.2.2/macos/libexec/uic
	/Users/thomasrio/Qt/6.2.2/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		infographic_extinction-main/Specie.hh \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		infographic_extinction-main/Specie.hh \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QString \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QCoreApplication \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qcoreapplication.h \
		ui_mainwindow.h \
		Animal.hh \
		Herbivorous.hh \
		Carnivorous.hh \
		infographic_extinction-main/CSVReader.hh \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QFile \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QTextStream \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qtextstream.h \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/QDir \
		../../../../Qt/6.2.2/macos/lib/QtCore.framework/Headers/qdir.h \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../../Qt/6.2.2/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Qt/6.2.2/macos/lib/QtGui.framework/Headers/QImage \
		../../../../Qt/6.2.2/macos/lib/QtGui.framework/Headers/qimage.h \
		../../../../Qt/6.2.2/macos/lib/QtGui.framework/Headers/QDesktopServices \
		../../../../Qt/6.2.2/macos/lib/QtGui.framework/Headers/qdesktopservices.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/animals22/bin || mkdir -p $(INSTALL_ROOT)/opt/animals22/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/animals22/bin/animals22.app
	
	$(QINSTALL) animals22.app $(INSTALL_ROOT)/opt/animals22/bin/animals22.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/animals22/bin/animals22.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/animals22/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

