import os
from simple_image_download import simple_image_download as simp

def main() :
	response = simp.simple_image_download
	#"Giant aye-aye","Malagasy hippopotamus","Microgale macpheei","Voay robustus","Giant fossa","Archaeoindris","Archaeolemur","Babakotia","Hadropithecus","Lava mouse","Mesopropithecus","Canary Islands giant rat","Koala lemur","Large sloth lemur","Ascension night heron","Elephant bird",
	#"Saint Helena dove","Saint Helena rail","Small Saint Helena petrel","Saint Helena hoopoe","Mauritian giant skink","Large Saint Helena petrel","Saint Helena crake","Mauritian giant skink","Ascension flightless crake","Mauritius night-heron","Réunion night heron","Réunion rail","Réunion owl","Dodo","Broad-billed parrot","Mauritian duck","Mauritian shelduck","Réunion shelduck","Réunion shelduck","Mascarene coot","Réunion kestrel",
	#"Réunion pink pigeon","Réunion pigeon","Red rail","Réunion kestrel","Réunion night-heron","Réunion owl","Réunion flightless ibis","Domed Mauritius giant tortoise","Saddle-backed Mauritius giant tortoise","Réunion ibis",
	#"Reunion gallinule","Rodrigues night-heron","Rodrigues owl"
	#"Rodrigues parrot","Rodrigues rail","Rodrigues starling","Réunion swamphen","Réunion parakeet","Mascarene grey parakeet","Mauritius grey parrot","Rodrigues solitaire","Réunion giant tortoise","Bluebuck","Domed Rodrigues giant tortoise","Saddle-backed Rodrigues giant tortoise","Delalande's coua","Mascarene parrot","Mascarene parrot","Mauritius blue pigeon","Rodrigues giant day gecko","Réunion giant tortoise","Mauritius owl","Réunion starling","Bourbon crested starling","Saint Helena cuckoo","Tristan moorhen","Lesser Mascarene flying fox","Lesser Mascarene flying fox","Cape warthog","Newton's parakeet","Cape lion","Atlas bear","Quagga","Seychelles parakeet","Red gazelle","De Winton's golden mole","Eastwood's long-tailed seps","Rodrigues day gecko","Madeiran wood pigeon","Bubal hartebeest","Ethiopian amphibious rat","Roque Chico de Salmor giant lizard","Salmo pallaryi","Canary Islands oystercatcher","Cape Verde giant skink","Du Toit's torrent frog","Ptychochromis onilahy","Round Island burrowing boa","Wimmer's shrew","Aplocheilichthys sp. nov. 'Naivasha'","Aldabra brush-warbler","Alaotra grebe","Eastern Canary Islands chiffchaff","Western black rhinoceros","Osgood's Ethiopian toad","Atlas wild ass","North African elephant","Damaliscus hysodon","Hipposideros besaoka","Bibymalagasy","Megaceroides algericus","Megalotragus","Syncerus (formerly Pelorovis) antiquus","Mauritius starling","Aurochs","Cape serval","Kenya oribi","Robert's lechwe","Canary Islands quail","Lagrand's ground roller","Hoffstetter's worm snake","Mozambique centipede-eater","Togo slippery frog","Barbus microbarbis","Pantanodon madagascariensis","Buhler's coryphomys","Flores cave rat",
	#"Flores long-nosed rat","Verhoeven's giant tree rat","Aurochs","Steller's sea cow","Bonin thrush","Bonin grosbeak","Black-browed babbler","Spectacled cormorant","Pseudophilautus leucorhinus","Caucasian elk","Pseudophilautus maia","Pseudophilautus temporalis","Siau scops owl","Pseudophilautus nanus","Pseudophilautus nasutus","Pseudophilautus oxyrhynchus","Himalayan quail","Pseudophilautus pardus","Gunther's streamlined frog","Pseudophilautus extirpo","Pseudophilautus adspersus","Ryukyu kingfisher","Hokkaidō wolf",
	#"Honshū wolf","Rück's blue flycatcher","Caucasian wisent","Pseudophilautus rugatus","Pseudophilautus zimmeri","Bering cackling goose","Vaurie's nightjar","Indian Javan rhinoceros","Mukojima white-eye","Pseudophilautus dimbullae","Pseudophilautus eximius","Ryukyu wood pigeon","Schomburgk's deer","Javan lapwing","Bali tiger","Pseudophilautus zal","Cyprus dipper","Queen of Sheba's gazelle","Ilin Island cloudrunner","Negros fruit dove","Pink-headed duck","Gloomy tube-nosed bat","Arabian ostrich","Catanduanes bleeding heart","Japanese sea lion","Acanthobrama hulensis","Siamese flat-barbelled catfish","Japanese river otter","Yunnan lake newt","Caspian tiger","Javan tiger","Tristramella intermedia","White-eyed river martin","Cyprinus yilongensis","Crested shelduck","Malabar civet","Kouprey","Slender-billed curlew","Gokce baligi","Formosan clouded leopard","Cebu warty pig","Baiji","Vietnamese Javan rhinoceros","Cave lion","Chinese elephant","Elasmotherium","Giant tapir","Giant deer","Stegodon","Steppe wisent","Syrian elephant","Woolly mammoth","Woolly rhinoceros","Asian ostrich","Bennu heron","Megalochelys atlas","Cyprus dwarf hippopotamus","Northern Sumatran rhinoceros","Saudi gazelle","Sturdee's pipistrelle","Cebu hanging parrot","Pseudophilautus malcolmsmithi","Pseudophilautus variabilis","Tristramella magdelainae","brown bear","Lion",
	#"European elk","Canary Islands giant rats Canariomys bravoi and Canariomys tamarani","White stork",
	lst = ["Sardinian giant shrew","Atlantic gray whale","Aurochs","Aurochs","Brown bear","Common sturgeon of Europe","Zope","European mink","Garden dormouse","Sardinian pika","Western capercaillie","Carpathian wisent","Eurasian spoonbill","Saiga antelope","Great bustard","Pied avocet","Great auk","Great auk","Caucasian elk","Chondrostoma scodrense","Northern goshawk","Western marsh harrier","European mink","Coregonus restrictus","Danube delta gudgeon","Portuguese ibex","Tarpan","Tarpan","Osprey"]

	for rep in lst :
	    response().download(rep, 3)
	    print(rep.replace(' ', '_'))
	    try :
		    os.remove("simple_images/" + rep.replace(' ', '_') + "/" + rep + "_1.png")
		    os.remove("simple_images/" + rep.replace(' ', '_') + "/" + rep + "_2.png")
		    os.rename("simple_images/" + rep.replace(' ', '_') + "/" + os.listdir("simple_images/" + rep.replace(' ', '_') + "/")[0], "simple_images/" + rep.replace(' ', '_') + "/" + rep.replace(' ', '_') + "." + os.listdir("simple_images/" + rep.replace(' ', '_') + "/")[0].split('.')[1])
	    except FileExistsError as e :
	    	   	print(e)

if __name__ == "__main__" :
	main()